name: Build dev

on:
  push:
    branches: [master]

jobs:
  build:
    name: Build and upload artifact
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Setup .NET Core SDK 6.0
        uses: subosito/flutter-action@v2

      - name: Build
        run: dotnet build -o .\outputs\test1.zip

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: Build ${{ github.run_number }}
          path: .\outputs\test1.zip

      - name: Upload docs
        uses: actions/upload-artifact@v3
        with:
          name: Docs ${{ github.run_number }}
          path: .\outputs\test1.zip
